const fs = require("fs");
const width = 750;
const height = 1200;
const dir = __dirname;
const description = "This NFT is part of The Bee Collaborative Collection | Save the Bees with NFTs!";
const baseImageUri = "https://gateway.ipfs.io/ipns/k51qzi5uqu5dhl0enp0dupzorbyhsmsdj1aewjbghr0se5kb1w1s65dof038g5";
const startEditionFrom = 1; // Can start edition at whatever you want // start at 1
const endEditionAt = 10; // endEditionAt and edtionSize MUST be the SAME // start at 10 for testing purposes
const editionSize = 10; // this will print 100 copies : (use if you already have a 10k 1 1st edition) // erase the 100
const raceWeights = [
  {
    value: "TweeTheBee", // Change to whatever you want
    from: 1,
    to: editionSize,
  },
];

const races = {
  TweeTheBee: { // Must bee the same as value on line 12 | ALL CAPITALIZATIONS MATTER
    name: "TweeTheBee", 
    layers: [
      {
        name: "Background",
        elements: [
          { 
            id: 0,
            name: "Astronaut",
            path: `${dir}/1-background/astronaut.png`, // 1-backround = folder name/png name
            weight: 70,
          },
          {
            id: 1,
            name: "Blue Spiral",
            path: `${dir}/1-background/bluespiral.png`,
            weight: 69,
          },
          {
            id: 2,
            name: "Dark Swirl",
            path: `${dir}/1-background/darkswirl_r.png`,
            weight: 68,
          },
          {
            id: 3,
            name: "Sherbert",
            path: `${dir}/1-background/sherbert.png`,
            weight: 67,
          },
          {
            id: 4,
            name: "Acryllica",
            path: `${dir}/1-background/acryllica.png`,
            weight: 65,
          },
          {
            id: 5,
            name: "BadAcid",
            path: `${dir}/1-background/badacid.png`,
            weight: 63,
          },
          {
            id: 6,
            name: "Blurple",
            path: `${dir}/1-background/blurple.png`,
            weight: 62,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Extra",
        elements: [
          {
            id: 0,
            name: "Alien Egg",
            path: `${dir}/2-extra/alienegg.png`,
            weight: 70,
          },
          {
            id: 1,
            name: "Bald Eagle",
            path: `${dir}/2-extra/bald eagle.png`,
            weight: 69,
          },
          {
            id: 2,
            name: "Bees",
            path: `${dir}/2-extra/bees.png`,
            weight: 68,
          },
          {
            id: 3,
            name: "Blood",
            path: `${dir}/2-extra/blood.png`,
            weight: 66,
          },
          {
            id: 4,
            name: "Bright Explosion",
            path: `${dir}/2-extra/brightsplosion.png`,
            weight: 65,
          },
          {
            id: 5,
            name: "Christmas Lights",
            path: `${dir}/2-extra/christmas lights.png`,
            weight: 64,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Character",
        elements: [
          {
            id: 0,
            name: "TweeTheBee",
            path: `${dir}/3-character/TweeTheBee.png`,
            weight: 70,
          },
          {
            id: 1,
            name: "Twee Blue Wings",
            path: `${dir}/3-character/Twee Blue Wings.png`,
            weight: 40,
          },
          {
            id: 2,
            name: "Twee Pink Wings",
            path: `${dir}/3-character/Twee Pink Wings_r.png`,
            weight: 30,
          },
          {
            id: 3,
            name: "Twee Purple Wings",
            path: `${dir}/3-character/Twee Purple Wings_r.png`,
            weight: 20,
          },
          {
            id: 4,
            name: "Twee Green Wings",
            path: `${dir}/3-character/Twee Green Wings.png`,
            weight: 10,
          },
          {
            id: 5,
            name: "Twee Black Wings",
            path: `${dir}/3-character/Twee Black Wings_ur.png`,
            weight: 3,
          },
          {
            id: 6,
            name: "Twee Rainbow Wings",
            path: `${dir}/3-character/Twee Rainbow Wings_ur.png`,
            weight: 1,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Prop",
        elements: [
          {
            id: 0,
            name: "Acoustic Guitar",
            path: `${dir}/4-prop/acoustic guitar.png`,
            weight: 70,
          },
          {
            id: 1,
            name: "Viking Warhammer Stein",
            path: `${dir}/4-prop/viking warhammer stein_ur.png`,
            weight: 69,
          },
          {
            id: 2,
            name: "Fire Axe",
            path: `${dir}/4-prop/axe_r.png`,
            weight: 68,
          },
          {
            id: 3,
            name: "War Axe",
            path: `${dir}/4-prop/waraxe_r.png`,
            weight: 67,
          },
          {
            id: 4,
            name: "Wine Glass",
            path: `${dir}/4-prop/wineglass_r.png`,
            weight: 66,
          },
          {
            id: 5,
            name: "Vodka",
            path: `${dir}/4-prop/vodka_r.png`,
            weight: 65,
          },
          {
            id: 6,
            name: "Sword",
            path: `${dir}/4-prop/sword_r.png`,
            weight: 64,
          },
          {
            id: 7,
            name: "Surfboard",
            path: `${dir}/4-prop/surfboard_r.png`,
            weight: 63,
          },
          {
            id: 8,
            name: "Sunburst Electric Guitar",
            path: `${dir}/4-prop/sunburst electric guitar_ur.png`,
            weight: 62,
          },
          {
            id: 9,
            name: "St.Patricks Beer",
            path: `${dir}/4-prop/st.patricks beer_r.png`,
            weight: 61,
          },
          {
            id: 10,
            name: "Snowboard",
            path: `${dir}/4-prop/snowboard_r.png`,
            weight: 60,
          },
          {
            id: 11,
            name: "Scepter",
            path: `${dir}/4-prop/scepter_r.png`,
            weight: 59,
          },
          {
            id: 12,
            name: "Portal Gun",
            path: `${dir}/4-prop/portal gun_r.png`,
            weight: 58,
          },
          {
            id: 13,
            name: "Pink Cuffs",
            path: `${dir}/4-prop/pink cuffs_r.png`,
            weight: 57,
          },
          {
            id: 14,
            name: "Moon Wand",
            path: `${dir}/4-prop/moon wand_r.png`,
            weight: 56,
          },
          {
            id: 15,
            name: "Money Wad",
            path: `${dir}/4-prop/moneywad_ur.png`,
            weight: 55,
          },
          {
            id: 16,
            name: "Mixed Drink",
            path: `${dir}/4-prop/mixed drink_r.png`,
            weight: 54,
          },
          {
            id: 17,
            name: "Electric Guitar",
            path: `${dir}/4-prop/greenelectric guitar_r.png`,
            weight: 53,
          },
          {
            id: 18,
            name: "Drumsticks",
            path: `${dir}/4-prop/drumsticks_r.png`,
            weight: 52,
          },
          {
            id: 19,
            name: "Devil's Pitchfork",
            path: `${dir}/4-prop/devils pitchfork_ur.png`,
            weight: 51,
          },
          {
            id: 20,
            name: "Xbox Controller",
            path: `${dir}/4-prop/controller_r.png`,
            weight: 5,
          },
          {
            id: 21,
            name: "Champagne",
            path: `${dir}/4-prop/champagne_r.png`,
            weight: 49,
          },
          {
            id: 22,
            name: "Briefcase",
            path: `${dir}/4-prop/briefcase_r.png`,
            weight: 48,
          },
          {
            id: 23,
            name: "Bong",
            path: `${dir}/4-prop/bong_ur.png`,
            weight: 47,
          },
          {
            id: 24,
            name: "Beer",
            path: `${dir}/4-prop/beer_r.png`,
            weight: 46,
          },
          {
            id: 25,
            name: "Skateboard",
            path: `${dir}/4-prop/skateboard_r.png`,
            weight: 45,
          },
          {
            id: 26,
            name: "Witchs Broom",
            path: `${dir}/4-prop/witchsbroom.png`,
            weight: 44,
          },
          {
            id: 27,
            name: "Tennis",
            path: `${dir}/4-prop/tennis.png`,
            weight: 43,
          },
          {
            id: 28,
            name: "Taco",
            path: `${dir}/4-prop/taco.png`,
            weight: 42,
          },
          {
            id: 29,
            name: "Syringe",
            path: `${dir}/4-prop/syringe.png`,
            weight: 41,
          },
          {
            id: 30,
            name: "Icecream",
            path: `${dir}/4-prop/strawberry icecream.png`,
            weight: 40,
          },
          {
            id: 31,
            name: "Squirt Gun",
            path: `${dir}/4-prop/squirt gun.png`,
            weight: 39,
          },
          {
            id: 32,
            name: "Soda",
            path: `${dir}/4-prop/soda.png`,
            weight: 38,
          },
          {
            id: 33,
            name: "Soccer Ball",
            path: `${dir}/4-prop/soccer ball.png`,
            weight: 37,
          },
          {
            id: 34,
            name: "Sketch Book",
            path: `${dir}/4-prop/sketchbook.png`,
            weight: 36,
          },
          {
            id: 35,
            name: "Rose",
            path: `${dir}/4-prop/rose.png`,
            weight: 35,
          },
          {
            id: 36,
            name: "Pizza",
            path: `${dir}/4-prop/pizza.png`,
            weight: 34,
          },
          {
            id: 37,
            name: "Painter",
            path: `${dir}/4-prop/painter.png`,
            weight: 33,
          },
          {
            id: 38,
            name: "None",
            path: `${dir}/4-prop/none.png`,
            weight: 32,
          },
          {
            id: 39,
            name: "Moneybag",
            path: `${dir}/4-prop/moneybag.png`,
            weight: 31,
          },
          {
            id: 40,
            name: "Martini",
            path: `${dir}/4-prop/martini.png`,
            weight: 30,
          },
          {
            id: 41,
            name: "Magical Wand",
            path: `${dir}/4-prop/magical wand.png`,
            weight: 29,
          },
          {
            id: 42,
            name: "Knife",
            path: `${dir}/4-prop/knife.png`,
            weight: 28,
          },
          {
            id: 43,
            name: "Judge Gavel",
            path: `${dir}/4-prop/judge gavel.png`,
            weight: 27,
          },
          {
            id: 44,
            name: "Iced Tea",
            path: `${dir}/4-prop/iced tea.png`,
            weight: 26,
          },
          {
            id: 45,
            name: "Iced Coffee",
            path: `${dir}/4-prop/iced coffee.png`,
            weight: 25,
          },
          {
            id: 46,
            name: "Hotdog",
            path: `${dir}/4-prop/hotdog.png`,
            weight: 24,
          },
          {
            id: 47,
            name: "Honeypot",
            path: `${dir}/4-prop/honeypot.png`,
            weight: 23,
          },
          {
            id: 48,
            name: "Hamburger",
            path: `${dir}/4-prop/hamburger.png`,
            weight: 22,
          },
          {
            id: 49,
            name: "Grenade",
            path: `${dir}/4-prop/grenade.png`,
            weight: 21,
          },
          {
            id: 50,
            name: "Frappe",
            path: `${dir}/4-prop/frappe.png`,
            weight: 20,
          },
          {
            id: 51,
            name: "Football",
            path: `${dir}/4-prop/football.png`,
            weight: 19,
          },
          {
            id: 52,
            name: "Fishing Pole",
            path: `${dir}/4-prop/fishingpole.png`,
            weight: 18,
          },
          {
            id: 53,
            name: "Explosive",
            path: `${dir}/4-prop/explosive.png`,
            weight: 17,
          },
          {
            id: 54,
            name: "Donut",
            path: `${dir}/4-prop/donut.png`,
            weight: 16,
          },
          {
            id: 55,
            name: "Controller",
            path: `${dir}/4-prop/controller blue.png`,
            weight: 15,
          },
          {
            id: 56,
            name: "Coffee",
            path: `${dir}/4-prop/coffee.png`,
            weight: 14,
          },
          {
            id: 57,
            name: "Coffee Cup",
            path: `${dir}/4-prop/coffee cup.png`,
            weight: 13,
          },
          {
            id: 58,
            name: "Chocolate Icecream",
            path: `${dir}/4-prop/chocolate swirl icecream.png`,
            weight: 12,
          },
          {
            id: 59,
            name: "Chainsaw",
            path: `${dir}/4-prop/chainsaw.png`,
            weight: 11,
          },
          {
            id: 60,
            name: "Camera",
            path: `${dir}/4-prop/camera.png`,
            weight: 10,
          },
          {
            id: 61,
            name: "Boombox",
            path: `${dir}/4-prop/boombox.png`,
            weight: 9,
          },
          {
            id: 62,
            name: "Bomb",
            path: `${dir}/4-prop/bomb.png`,
            weight: 8,
          },
          {
            id: 63,
            name: "Boba Tea",
            path: `${dir}/4-prop/boba tea.png`,
            weight: 7,
          },
          {
            id: 64,
            name: "BasketBall",
            path: `${dir}/4-prop/basketball.png`,
            weight: 6,
          },
          {
            id: 65,
            name: "Baseball Bat",
            path: `${dir}/4-prop/baseball bat.png`,
            weight: 5,
          },
          {
            id: 66,
            name: "Acoustic Guitar Blue",
            path: `${dir}/4-prop/blue acoustic guitar_r.png`,
            weight: 4,
          },
          {
            id: 67,
            name: "Electric Bass",
            path: `${dir}/4-prop/electric bass guitar_r.png`,
            weight: 3,
          },
          {
            id: 68,
            name: "None",
            path: `${dir}/4-prop/none.png`,
            weight: 2,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Expression",
        elements: [
          {
            id: 0,
            name: "Smile",
            path: `${dir}/5-expression/smile.png`,
            weight: 70,
          },
          {
            id: 1,
            name: "Surprised",
            path: `${dir}/5-expression/surprised.png`,
            weight: 50,
          },
          {
            id: 2,
            name: "Shocked",
            path: `${dir}/5-expression/shocked_r.png`,
            weight: 42,
          },
          {
            id: 3,
            name: "Indifferent",
            path: `${dir}/5-expression/neutral.png`,
            weight: 34,
          },
          {
            id: 4,
            name: "Laugh",
            path: `${dir}/5-expression/laugh_r.png`,
            weight: 26,
          },
          {
            id: 5,
            name: "Gasp",
            path: `${dir}/5-expression/gasp_r.png`,
            weight: 19,
          },
          {
            id: 6,
            name: "Biting Lip",
            path: `${dir}/5-expression/biting lip.png`,
            weight: 12,
          },
          {
            id: 7,
            name: "Fangs",
            path: `${dir}/5-expression/fangs_ur.png`,
            weight: 5,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Face",
        elements: [
          {
            id: 0,
            name: "None",
            path: `${dir}/6-face/none.png`,
            weight: 70,
          },
          {
            id: 1,
            name: "Bandaid",
            path: `${dir}/6-face/bandaid.png`,
            weight: 65,
          },
          {
            id: 2,
            name: "Bowtie Orange",
            path: `${dir}/6-face/bowtie orange.png`,
            weight: 61,
          },
          {
            id: 3,
            name: "Bowtie Red",
            path: `${dir}/6-face/bowtie red.png`,
            weight: 57,
          },
          {
            id: 4,
            name: "Bowtie Spotted",
            path: `${dir}/6-face/bowtie spotted.png`,
            weight: 53,
          },
          {
            id: 5,
            name: "Double Scratch",
            path: `${dir}/6-face/double scratch.png`,
            weight: 49,
          },
          {
            id: 6,
            name: "Lip Dirt",
            path: `${dir}/6-face/lip dirt.png`,
            weight: 45,
          },
          {
            id: 7,
            name: "Mustache",
            path: `${dir}/6-face/mustache.png`,
            weight: 41,
          },
          {
            id: 8,
            name: "Mustachio",
            path: `${dir}/6-face/mustachio.png`,
            weight: 37,
          },
          {
            id: 9,
            name: "Bloody Handprint",
            path: `${dir}/6-face/bloody handprint_r.png`,
            weight: 33,
          },
          {
            id: 10,
            name: "Bloody Swipe",
            path: `${dir}/6-face/bloody swipe_r.png`,
            weight: 29,
          },
          {
            id: 11,
            name: "Covid Mask",
            path: `${dir}/6-face/facemask_r.png`,
            weight: 25,
          },
          {
            id: 12,
            name: "Flame Scar",
            path: `${dir}/6-face/flame scar_ur.png`,
            weight: 21,
          },
          {
            id: 13,
            name: "Gas Mask",
            path: `${dir}/6-face/gasmask_r.png`,
            weight: 18,
          },
          {
            id: 14,
            name: "Kiss",
            path: `${dir}/6-face/kiss_r.png`,
            weight: 14,
          },
          {
            id: 15,
            name: "Mustache Italiano",
            path: `${dir}/6-face/mustache italiano_r.png`,
            weight: 10,
          },
          {
            id: 16,
            name: "Tribal Tattoo",
            path: `${dir}/6-face/tribaltattoo_r.png`,
            weight: 6,
          },
          {
            id: 17,
            name: "Werewolf Swipe",
            path: `${dir}/6-face/werewolf swipe_ur.png`,
            weight: 3,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Eyewear",
        elements: [
          {
            id: 0,
            name: "None",
            path: `${dir}/7-eyewear/none.png`,
            weight: 70,
          },
          {
            id: 1,
            name: "3D Glasses",
            path: `${dir}/7-eyewear/3d glasses.png`,
            weight: 68,
          },
          {
            id: 2,
            name: "Clown Nose Glasses",
            path: `${dir}/7-eyewear/clown nose glasses.png`,
            weight: 66,
          },
          {
            id: 3,
            name: "Cucumber Eyes",
            path: `${dir}/7-eyewear/cucumber eyes.png`,
            weight: 64,
          },
          {
            id: 4,
            name: "Diamond Eyes",
            path: `${dir}/7-eyewear/diamond eyes.png`,
            weight: 62,
          },
          {
            id: 5,
            name: "False Nose Glasses",
            path: `${dir}/7-eyewear/false nose glasses.png`,
            weight: 60,
          },
          {
            id: 6,
            name: "Heart Eyes",
            path: `${dir}/7-eyewear/heart eyes.png`,
            weight: 58,
          },
          {
            id: 7,
            name: "Heart Shaped Glasses Pink",
            path: `${dir}/7-eyewear/heart shaped glasses pink.png`,
            weight: 56,
          },
          {
            id: 8,
            name: "Heart Shaped Glasses",
            path: `${dir}/7-eyewear/heart shaped glasses.png`,
            weight: 54,
          },
          {
            id: 9,
            name: "Kaleidoscope Eyes",
            path: `${dir}/7-eyewear/kaleidoscope eyes.png`,
            weight: 52,
          },
          {
            id: 10,
            name: "Kaleidoscope Rainbow Eyes",
            path: `${dir}/7-eyewear/kaleidoscope rainbow eyes.png`,
            weight: 50,
          },
          {
            id: 11,
            name: "Peppermint Eyes",
            path: `${dir}/7-eyewear/peppermint eyes.png`,
            weight: 48,
          },
          {
            id: 12,
            name: "Purple Shades",
            path: `${dir}/7-eyewear/purple shades.png`,
            weight: 46,
          },
          {
            id: 13,
            name: "Raybans",
            path: `${dir}/7-eyewear/raybans.png`,
            weight: 44,
          },
          {
            id: 14,
            name: "Shutter Shades Blue",
            path: `${dir}/7-eyewear/shutter shades blue.png`,
            weight: 42,
          },
          {
            id: 15,
            name: "Shutter Shades Pink",
            path: `${dir}/7-eyewear/shutter shades pink.png`,
            weight: 40,
          },
          {
            id: 16,
            name: "Shutter Shades",
            path: `${dir}/7-eyewear/shutter shades.png`,
            weight: 38,
          },
          {
            id: 17,
            name: "Sunglasses Red",
            path: `${dir}/7-eyewear/sunglasses red.png`,
            weight: 36,
          },
          {
            id: 18,
            name: "Sunglasses Vintage",
            path: `${dir}/7-eyewear/sunglasses vintage.png`,
            weight: 34,
          },
          {
            id: 19,
            name: "Tear Drop Tattoo",
            path: `${dir}/7-eyewear/tear drop tattoo.png`,
            weight: 32,
          },
          {
            id: 20,
            name: "Weed Eyes",
            path: `${dir}/7-eyewear/weed eyes.png`,
            weight: 30,
          },
          {
            id: 21,
            name: "Yellow Shades",
            path: `${dir}/7-eyewear/yellow shades.png`,
            weight: 28,
          },
          {
            id: 22,
            name: "Donut Eyes",
            path: `${dir}/7-eyewear/donut eyes_r.png`,
            weight: 26,
          },
          {
            id: 23,
            name: "Bleeding Eyes",
            path: `${dir}/7-eyewear/bleeding eyes_ur.png`,
            weight: 24,
          },
          {
            id: 24,
            name: "Fabulous",
            path: `${dir}/7-eyewear/fabulous_r.png`,
            weight: 22,
          },
          {
            id: 25,
            name: "Masquerade",
            path: `${dir}/7-eyewear/masquerade_r.png`,
            weight: 20,
          },
          {
            id: 26,
            name: "Monocle",
            path: `${dir}/7-eyewear/monocle_ur.png`,
            weight: 18,
          },
          {
            id: 27,
            name: "Pirate Patch",
            path: `${dir}/7-eyewear/pirate patch_r.png`,
            weight: 16,
          },
          {
            id: 28,
            name: "Scar",
            path: `${dir}/7-eyewear/scar_r.png`,
            weight: 14,
          },
          {
            id: 29,
            name: "Scuba",
            path: `${dir}/7-eyewear/scuba_r.png`,
            weight: 12,
          },
          {
            id: 30,
            name: "Ski Goggles",
            path: `${dir}/7-eyewear/ski goggles_r.png`,
            weight: 10,
          },
          {
            id: 31,
            name: "Sunglasses Beach",
            path: `${dir}/7-eyewear/sunglasses beach_r.png`,
            weight: 8,
          },
          {
            id: 32,
            name: "Sunglasses Cityscape",
            path: `${dir}/7-eyewear/sunglasses cityscape_r.png`,
            weight: 6,
          },
          {
            id: 33,
            name: "Sunglasses Vacation",
            path: `${dir}/7-eyewear/sunglasses vacation_r.png`,
            weight: 4,
          },
          {
            id: 34,
            name: "Sasuke Eye",
            path: `${dir}/7-eyewear/sasuke eye_ur.png`,
            weight: 2,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Headpiece",
        elements: [
          {
            id: 0,
            name: "Antennas",
            path: `${dir}/8-headpiece/antenna.png`,
            weight: 70,
          },
          {
            id: 1,
            name: "None",
            path: `${dir}/8-headpiece/none.png`,
            weight: 65,
          },
          {
            id: 2,
            name: "Captains Hat",
            path: `${dir}/8-headpiece/captains hat.png`,
            weight: 60,
          },
          {
            id: 3,
            name: "Chef Hat",
            path: `${dir}/8-headpiece/chefhat.png`,
            weight: 58,
          },
          {
            id: 4,
            name: "Cowboy Hat",
            path: `${dir}/8-headpiece/cowboy hat.png`,
            weight: 56,
          },
          {
            id: 5,
            name: "Dinner Party Hat",
            path: `${dir}/8-headpiece/dinner party hat.png`,
            weight: 54,
          },
          {
            id: 6,
            name: "Fire Fighter",
            path: `${dir}/8-headpiece/fire fighter.png`,
            weight: 52,
          },
          {
            id: 7,
            name: "Flower Crown",
            path: `${dir}/8-headpiece/flower crown.png`,
            weight: 50,
          },
          {
            id: 8,
            name: "Gentlemans Hat",
            path: `${dir}/8-headpiece/gentlemans hat.png`,
            weight: 47,
          },
          {
            id: 9,
            name: "Leprechaun Hat",
            path: `${dir}/8-headpiece/leprechaun.png`,
            weight: 45,
          },
          {
            id: 10,
            name: "Birthday Cactus Hat",
            path: `${dir}/8-headpiece/birthday cactus hat.png`,
            weight: 43,
          },
          {
            id: 11,
            name: "Nurse Hat",
            path: `${dir}/8-headpiece/nurse hat.png`,
            weight: 41,
          },
          {
            id: 12,
            name: "Party Hat",
            path: `${dir}/8-headpiece/party hat.png`,
            weight: 39,
          },
          {
            id: 13,
            name: "Police Hat",
            path: `${dir}/8-headpiece/police hat.png`,
            weight: 38,
          },
          {
            id: 14,
            name: "Red Hat Society",
            path: `${dir}/8-headpiece/red hat society.png`,
            weight: 36,
          },
          {
            id: 15,
            name: "Reindeer Antlers Pink",
            path: `${dir}/8-headpiece/reindeer pink.png`,
            weight: 35,
          },
          {
            id: 16,
            name: "Reindeer Antlers",
            path: `${dir}/8-headpiece/reindeer.png`,
            weight: 34,
          },
          {
            id: 17,
            name: "Rose Crown",
            path: `${dir}/8-headpiece/rose crown.png`,
            weight: 32,
          },
          {
            id: 18,
            name: "Sailor Hat",
            path: `${dir}/8-headpiece/sailor hat.png`,
            weight: 31,
          },
          {
            id: 19,
            name: "Santa Hat",
            path: `${dir}/8-headpiece/santa hat.png`,
            weight: 30,
          },
          {
            id: 20,
            name: "Silver Hat",
            path: `${dir}/8-headpiece/silver hat.png`,
            weight: 28,
          },
          {
            id: 21,
            name: "Tiara",
            path: `${dir}/8-headpiece/tiara.png`,
            weight: 26,
          },
          {
            id: 22,
            name: "Unclesam Hat",
            path: `${dir}/8-headpiece/unclesam hat.png`,
            weight: 24,
          },
          {
            id: 23,
            name: "Witch Hat",
            path: `${dir}/8-headpiece/witchhat.png`,
            weight: 22,
          },
          {
            id: 24,
            name: "Wizard Hat",
            path: `${dir}/8-headpiece/wizardhat.png`,
            weight: 21,
          },
          {
            id: 25,
            name: "Birthday Hat",
            path: `${dir}/8-headpiece/birthday hat_r.png`,
            weight: 20,
          },
          {
            id: 26,
            name: "Bunny Ears",
            path: `${dir}/8-headpiece/bunnyears_r.png`,
            weight: 19,
          },
          {
            id: 27,
            name: "Thorn Crown",
            path: `${dir}/8-headpiece/crown of thorns.png`,
            weight: 18,
          },
          {
            id: 28,
            name: "Dog Filter",
            path: `${dir}/8-headpiece/dog filter_r.png`,
            weight: 17,
          },
          {
            id: 29,
            name: "Gold Hat",
            path: `${dir}/8-headpiece/gold hat_r.png`,
            weight: 16,
          },
          {
            id: 30,
            name: "Halo",
            path: `${dir}/8-headpiece/halo_r.png`,
            weight: 15,
          },
          {
            id: 31,
            name: "Horns",
            path: `${dir}/8-headpiece/horns_r.png`,
            weight: 14,
          },
          {
            id: 32,
            name: "Jester Hat",
            path: `${dir}/8-headpiece/jester hat_r.png`,
            weight: 13,
          },
          {
            id: 33,
            name: "King Crown",
            path: `${dir}/8-headpiece/king crown_ur.png`,
            weight: 12,
          },
          {
            id: 34,
            name: "Madhatter",
            path: `${dir}/8-headpiece/madhatter_r.png`,
            weight: 11,
          },
          {
            id: 35,
            name: "Pirate Hat",
            path: `${dir}/8-headpiece/pirate hat_r.png`,
            weight: 10,
          },
          {
            id: 36,
            name: "Pumpkin Head",
            path: `${dir}/8-headpiece/pumpkin head_ur.png`,
            weight: 9,
          },
          {
            id: 37,
            name: "Queen Crown",
            path: `${dir}/8-headpiece/queen crown_r.png`,
            weight: 8,
          },
          {
            id: 38,
            name: "Rainbow Frow",
            path: `${dir}/8-headpiece/rainbow frow_r.png`,
            weight: 7,
          },
          {
            id: 39,
            name: "Reindeer Crown",
            path: `${dir}/8-headpiece/reindeer crown_ur.png`,
            weight: 6,
          },
          {
            id: 40,
            name: "Steampunk Hat",
            path: `${dir}/8-headpiece/steampunk hat_r.png`,
            weight: 5,
          },
          {
            id: 41,
            name: "Viking Cap",
            path: `${dir}/8-headpiece/viking helmet_r.png`,
            weight: 4,
          },
          {
            id: 42,
            name: "Unircorn Crown",
            path: `${dir}/8-headpiece/unicorn crown_ur.png`,
            weight: 3,
          },
          {
            id: 43,
            name: "Crown of Thorns",
            path: `${dir}/8-headpiece/crown of thorns_r.png`,
            weight: 2,
          },
          {
            id: 44,
            name: "Viking Helmet",
            path: `${dir}/8-headpiece/viking helmet_ur.png`,
            weight: 1,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
    ],
  },
};

module.exports = {
  width,
  height,
  description,
  baseImageUri,
  editionSize,
  startEditionFrom,
  endEditionAt,
  races,
  raceWeights,
};
